name: flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  http: ^0.12.0+2
  url_launcher: ^5.0.1
  path_provider: ^1.6.27


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
     - images/tasarÄ±m.JPG


  fonts:
     - family: Pacifico
       fonts:
         - asset: fonts/Pacifico-Regular.ttf

     - family: Tangerine
       fonts:
        - asset: fonts/Tangerine-Bold.ttf


